[Kafka-asset] Allow kafka to be restartable
terascope/kafka-assets pull request #838
Opened 2024-09-18 13:35 UTC by sotojn

This PR makes the following changes:

## New Features 

- Operation `kafka_reader` is now restartable when running in `kubernetesV2` in teraslice
  - This slicer is able to come back up in the event the pod is deleted in kubernetes. This includes use cases such as draining a node which would delete all resources from that node.

2024-09-18 14:29 UTC, busma13 commented on asset/src/kafka_reader/slicer.ts
> +    isRestartable(): boolean {
Are we certain that we are sticking with this name? I feel like once this name spreads out of Teraslice it will be harder to change.

2024-09-18 22:42 UTC, godber requested changes
Rename `isRestartable` to `isRelocatable`.

2024-09-18 22:42 UTC, godber commented on asset/src/kafka_reader/slicer.ts
> +    isRestartable(): boolean {
```suggestion
    isRelocatable(): boolean {
```

We've decided to switch to `isRelocatable`.  This should be changed here and in the appropriate places in Teraslice.  We will write an issue to consider adding a `relocating` state.

2024-10-28 16:56 UTC, godber approved these changes

2024-10-28 16:56 UTC, merged